# spring.application.name=StudentManagement

# # Cau hinh file Database SQLite (tu dong tao file students.db tai thu muc goc project)
# spring.datasource.url=jdbc:sqlite:student.db
# spring.datasource.driver-class-name=org.sqlite.JDBC
# # Cau hinh JPA/Hibernate
# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.config.import=optional:file:.env[.properties]
# 1. Thông tin kết nối đến PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình Hibernate tự động tạo/cập nhật Schema
spring.jpa.hibernate.ddl-auto=update

# 3. Các cấu hình phụ trợ giúp debug dễ dàng hơn (Tùy chọn)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
